"""initial_schema

Revision ID: b454555bb773
Revises: 
Create Date: 2026-08-06 18:09:28.498537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b454555bb773'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lat_round', sa.Float(), nullable=False),
    sa.Column('lon_round', sa.Float(), nullable=False),
    sa.Column('workload', sa.String(length=16), nullable=False),
    sa.Column('acclimatized', sa.Boolean(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_round', 'lon_round', 'workload', 'acclimatized', name='uq_assessment')
    )
    op.create_table('climatology_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lat_round', sa.Float(), nullable=False),
    sa.Column('lon_round', sa.Float(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed_ms', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('source_note', sa.String(length=128), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_round', 'lon_round', 'month', 'day', 'hour', name='uq_climatology_point')
    )
    op.create_table('fire_detections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lat_round', sa.Float(), nullable=False),
    sa.Column('lon_round', sa.Float(), nullable=False),
    sa.Column('bright_ti4', sa.Float(), nullable=True),
    sa.Column('bright_ti5', sa.Float(), nullable=True),
    sa.Column('scan', sa.Float(), nullable=True),
    sa.Column('track', sa.Float(), nullable=True),
    sa.Column('acq_date', sa.Date(), nullable=False),
    sa.Column('acq_time', sa.String(length=4), nullable=False),
    sa.Column('satellite', sa.String(length=16), nullable=False),
    sa.Column('instrument', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.String(length=16), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=True),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('daynight', sa.String(length=1), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_round', 'lon_round', 'acq_date', 'acq_time', 'satellite', name='uq_fire_detection')
    )
    op.create_index('ix_fire_bbox', 'fire_detections', ['longitude', 'latitude'], unique=False)
    op.create_table('forecast_hours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lat_round', sa.Float(), nullable=False),
    sa.Column('lon_round', sa.Float(), nullable=False),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_round', 'lon_round', 'valid_at', name='uq_forecast_hour')
    )
    op.create_index('ix_forecast_loc_time', 'forecast_hours', ['lat_round', 'lon_round', 'valid_at'], unique=False)
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fires_upserted', sa.Integer(), nullable=False),
    sa.Column('forecast_upserted', sa.Integer(), nullable=False),
    sa.Column('climatology_upserted', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('firms_quota_remaining', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('lat_round', sa.Float(), nullable=False),
    sa.Column('lon_round', sa.Float(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_llm_cache_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_calls')
    op.drop_table('ingest_runs')
    op.drop_index('ix_forecast_loc_time', table_name='forecast_hours')
    op.drop_table('forecast_hours')
    op.drop_index('ix_fire_bbox', table_name='fire_detections')
    op.drop_table('fire_detections')
    op.drop_table('climatology_points')
    op.drop_table('assessment_cache')
    # ### end Alembic commands ###
